### PR TITLE
possibly fix ringer

### PR DESCRIPTION
**Pull request by Fluidification**
hey guys, so this is the same fix that hampsterblade had proposed back in gingerbread.

### CODE REVIEW

**Comment by maxfierke** [comment]
We don't want possible fixes. We want actual fixes. Do not submit a pull
request until you have tested the change and it is working.

**Comment by Fluidification** [comment]
but really, I am 90% sure it will work.

**Comment by maxfierke** [comment]
My issue with this pull request is not really about the content of the patch, but more so the commit message and airfluip's continued submitting of "possible" fixes that he has not tested. Pull requests are for submitting changes that you have tested and have found to be working.

Airfluip, I understand that for various reasons you are not able to build CM yourself to test these changes, but the other developers and I are generally working on things ourselves and may not necessarily want to take the time out of what we're working on to test something that we don't necessarily know will lead to anything. It works a lot better when the person submitting code knows what it will do.

Instead of applying this same fix to libaudio, we're going to port crespo's audio driver and wm8994 extensions over to our kernel.

**Comment by Fluidification** [comment]
No problem max, Erikmm has already accepted the task of building it for me though, so if it works, can I post a link in the Dev thread for temporary fix?

**Comment by maxfierke** [comment]
That would be acceptable. Just make clear that it is a temporary fix.

Also, make sure you're only distributing the new libaudio and not anything extra. We don't want to introduce new variables to the playing field.

**Comment by Fluidification** [comment]
OK

**Pull request closed without merging**
